services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket 
    restart: unless-stopped
    privileged: true
    network_mode: host
